### ISSUE TITLE
Plotting issues

### ISSUE THREAD

**Issue by matthdsm** [CenterForMedicalGeneticsGhent/MultiQC_SAV#1]
Ping @ewels

Hi Phil,
Since I'm not sure if this is really a MultiQC issue, I'm reporting it here.
I'm experiencing some issues with the plots:
- when using interactive plots, the larger heatmap and line plot seem to be stuck in a `loading` state. How can I debug this?
- when using the `-fp` option, some plots, but not all are converted to a png image.
This seems to work for the barplot and one of the line plots, but for the scatter plot is still interactive, the heatmap is stuck on "loading" and another line plot doesn't show up at all.

Any help would be much appreciated.

Thanks
M

**Comment by ewels** [comment]
Can you attach a zipped report so I can take a look please? The loading thing usually means that the JavaScript has crashed.

**Comment by matthdsm** [comment]
Hi, 

Thanks for looking into this.
I've added a zip file containing an interactive and a flat plot.
[mqc_reports.zip](https://github.com/CenterForMedicalGeneticsGhent/MultiQC_SAV/files/6499614/mqc_reports.zip)

**Comment by ewels** [comment]
Yeah, this is a JavaScript error:

```console
multiqc_report_flat.html:2215 Uncaught TypeError: Cannot read property 'length' of undefined
    at plot_graph (multiqc_report_flat.html:2215)
    at multiqc_report_flat.html:1971
```

Could you please try running with the latest stable version of MultiQC? My guess (and hope) is that this is a relatively new bug that I added in the past few days when messing with the heatmap javascript.

If it's possible to upload some input files so that I can replicate this at my end that would be very helpful.

**Comment by ewels** [comment]
> * This seems to work for the barplot and one of the line plots, but for the scatter plot is still interactive, the heatmap is stuck on "loading" and another line plot doesn't show up at all.

Yup, scatter, heatmap and beeswarm plots do not have flat plot equivalents sadly. Been meaning to write this code since 2016 (https://github.com/ewels/MultiQC/issues/204, https://github.com/ewels/MultiQC/issues/281, https://github.com/ewels/MultiQC/issues/282). It's not trivial code 😓 

I'm kind of hoping to switch to Plotly in a future v2.0 rewrite of MultiQC, which will give many more plot types and also cli flat plot generation out of the box without the need for custom code. But that will be a big rewrite. One day...

**Comment by matthdsm** [comment]
I re-ran with the latest stable MultiQC, but got the same result.
[mqc_reports_stable.zip](https://github.com/CenterForMedicalGeneticsGhent/MultiQC_SAV/files/6500237/mqc_reports_stable.zip)
Anything I can do to help fix this?

Its good to dream! Here's hoping there's time (and funding) to lift MultiQC to new heights!

**Comment by matthdsm** [comment]
FYI, there's test data for several sequencers in the repo if you need something to test this with.

**Comment by ewels** [comment]
Ok interesting, so it's _not_ my new code changes! Yes if you could point me to some data to run on to replicate this locally that would be great..

**Comment by matthdsm** [comment]
Test data is here: https://github.com/CenterForMedicalGeneticsGhent/MultiQC_SAV/tree/main/test_data

**Comment by matthdsm** [comment]
Also, If this module can get your stamp of approval, feel free to add it to the MultiQC organisation.
Do I maintain write rights if the module gets moved? This is only a first draft, but I've got the feeling there's room for improvement. There's also bound to be a bunch of feature requests coming from the users.

**Comment by ewels** [comment]
> Do I maintain write rights if the module gets moved?

I would add you as a collaborator, so yes. I can also then add it to https://multiqc.info/plugins.html

**Comment by matthdsm** [comment]
Sounds great! Feel free to open this up to the public!

**Comment by matthdsm** [comment]
There's a logo in the docs, if you need one to add to  https://multiqc.info/plugins.html

**Comment by ewels** [comment]
There is? Where? I can only see the MultiQC logo..

Need to do a few things before forking..

* Fix this bug ☝🏻 
* Test / review the plugin as I would with a regular module

So won't be immediate..

**Comment by matthdsm** [comment]
oh, my bad, there used to be one, but I moved the custom template to a different repo.
You can find one [here](https://github.com/CenterForMedicalGeneticsGhent/MultiQC_CMGG/blob/main/docs/images/CMGG_logo.png).

If there's anything I can do to help this along, feel free to let me know.

M

**Comment by ewels** [comment]
> If there's anything I can do to help this along, feel free to let me know.

Keep bugging me :) I have a lot of people shouting to get stuff done so the louder you shout the faster it will likely happen (within reason 😅). Popping an issue up on onto the main MultiQC repo would help with that 👍🏻

**Comment by ewels** [comment]
If you want to skip ahead (I have a grant deadline tomorrow etc) then what I would do first is to print out the data structure that you're passing to the plotting function. I've never seen this error before but my guess is that the data structure does not exactly match what MultiQC expects.

```
TypeError: undefined is not an object (evaluating 'mqc_plots[target]["xcats"][0].length')
```

This sounds like there are no x-axis categories being set ☝🏻

**Comment by ewels** [comment]
Yeah: https://github.com/CenterForMedicalGeneticsGhent/MultiQC_SAV/blob/325d226336e5ffcc90ca6e70faa3fe1392390d81/multiqc_sav/modules/sav.py#L551

Should be `heatmap.plot(data, xcats, ycats, pconfig)` : https://multiqc.info/docs/#heatmaps

**Comment by ewels** [comment]
Ok great! 🚀 The error message looked similar for the linegraph so I guess it's the same thing there..

**Comment by matthdsm** [comment]
Turns out both issue were my fault...
I forgot to add the x and y cats for the heatmap, like you said, en there was a typo in a variable name for the line plot.

All good to go now!

**Comment by ewels** [comment]
Sorry for the non-intuitive mode of failure. Should probably add some checks for this / raise an exception if not all required arguments are there etc.

Glad it's sorted!

**Comment by matthdsm** [comment]
Hi Phil,

Another quick question. Is there a way to adjust the default size of the heatmap? as it is now, it's a bit awkwardly placed and pulled to the left. It's also hard to see the cells when there's a lot of datapoints.
I'm aware I can disable the square format, but that doesn't really help much for visibility.

Thanks
M

**Comment by ewels** [comment]
You can drag the little grey bar down underneath it (as with any MultiQC plot). But there's no way to initialise it at a bigger size, no.

**Comment by matthdsm** [comment]
Bummer, seems like my users will have to drag then, no biggie!

Thanks for the info.
M

**Comment by ewels** [comment]
Feel free to make an issue - I guess it would be relatively simple to add a plot config option for this 🤔
